#!/bin/sh

system_type=$(uname -s)
system_arch=$(uname -m)

function install_brew () {
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
}

if [ "$system_type" = "Darwin" ]; then
  install_brew
fi
# Linux on Arm64 is not supported by homebrew
if [ "$system_type" = "Linux" ] && [ "$system_arch" != "aarch64" ]; then
  install_brew
fi

