#!/bin/sh

system_type=$(uname -s)
system_arch=$(uname -m)
apt_list_file=$HOME/.config/yadm/apt.list

# Installation step for unix systems
# This step will run on both linux and macos
install_unix () {
  # Install pyenv
  # Pyenv convenience script is for unix
  curl https://pyenv.run | bash
}

# Installation step for macos(mainly)
install_brew () {
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
}

# Installation step for debian based linux
install_apt () {
  echo "Installing apt packages"
  sudo apt update
  cat $apt_list_file | xargs sudo apt install -y
}

# Actual installation by calling the functions
if [ "$system_type" = "Darwin" ]; then
  install_unix
  install_brew
fi

if [ "$system_type" = "Linux" ]; then
  distribution=$(cat /etc/*-release | grep -e '^NAME=".*"$' | cut -c 6- | xargs)

  # Debian based
  if [ "$distribution" = 'Ubuntu' ] || [ "$distribution" = 'Debian' ]; then
    install_unix
    install_apt 
  else
    echo "Unsupported linux distribution($distribution)"
    exit 1
  fi
fi

