#!/bin/bash

ESC=$(printf '\033')
BOLD="${ESC}[1m"
RED="${ESC}[31m"
GREEN="${ESC}[32m"
BOLD_GREEN="${ESC}[1;32m"
RESET="${ESC}[0m"

system_type=$(uname -s)
system_arch=$(uname -m)
apt_list_file=$HOME/.config/yadm/apt.list

# Installation step for unix systems
# This step will run on both linux and macos
install_unix () {
  echo $BOLD_GREEN "Installation for unix systems" $RESET
  # Install pyenv
  # Pyenv convenience script is for unix
  export PYENV_ROOT="$HOME/.local/share/pyenv"
  echo $BOLD_GREEN "Installing pyenv" $RESET
  curl https://pyenv.run | bash
  fish_add_path $HOME/.local/share/pyenv/bin
}

# Installation step for homebrew
install_homebrew () {
  echo $BOLD_GREEN "Installation by homebrew" $RESET
  if ! command -v brew >/dev/null 2>&1; then
    echo $BOLD_GREEN "Installing missing brew command"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
}

# Installation step for debian based linux
install_apt () {
  echo $BOLD_GREEN "Installation by apt" $RESET
  sudo apt update
  cat $apt_list_file | xargs sudo apt install -y
}

add_apt_repo_ubuntu () {
  echo "$BOLD_GREEN" "Adding apt repository for ubuntu" "$RESET"
  sudo apt-add-repository ppa:fish-shell/release-3
}

configure_fish () {
  echo $BOLD_GREEN "Configuring fish" $RESET
  echo $BOLD_GREEN "Installling fisher" $RESET
  fish $HOME/.config/yadm/bootstrap.fish
}

configure_neovim () {
  echo "$BOLD_GREEN" "Installing vim-plug" "$RESET"
  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  if command -v nvim >/dev/null 2>&1; then
    echo "$BOLD_GREEN" "Bootstraping Vim" "$RESET"
    nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
  fi
}

# Actual installation by calling the functions
if [ "$system_type" = "Darwin" ]; then
  install_unix
  install_homebrew
  configure_fish
  configure_neovim
fi

if [ "$system_type" = "Linux" ]; then
  distribution=$(cat /etc/*-release | grep -e '^NAME=".*"$' | cut -c 6- | xargs)

  if [[ $distribution == *"Ubuntu"* ]]; then
    install_unix
    add_apt_repo_ubuntu
    install_apt
    install_homebrew
    configure_fish
    configure_neovim
  elif [[ $distribution == *"Debian"* ]]; then
    install_unix
    add_apt_repo_debian
    install_apt 
    install_homebrew
    configure_fish
    configure_neovim
  else
    echo "Unsupported linux distribution($distribution)"
    exit 1
  fi
fi
